[project]
name = "sistema-hospitalar"
version = "0.1.0"
description = ""
authors = [
    {name = "Aluno"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.136.1,<0.137.0)",
    "sqlalchemy (>=2.0.0)",
    "pydantic-settings (>=2.0.0)",
    "alembic (>=1.13.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
